name: skeleton
description: "Personal flutter app template."
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  logger: ^2.6.1
  uuid: ^4.5.1
  device_info_plus: ^11.3.0

  flutter_tabler_icons: any
  hive_ce: ^2.11.3 # common hive is deprecated
  hive_ce_flutter: ^2.3.1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  http: ^1.4.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_boring_avatars: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_ce_generator: ^1.9.3
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
    - assets/images/
    - assets/svg/

  fonts:
    - family: GeistMono
      fonts:
        - asset: fonts/GeistMono-Regular.ttf
        - asset: fonts/GeistMono-Bold.ttf
          weight: 700
  # see https://flutter.dev/to/font-from-package
